Collecting Django==3.1.5 (from -r D:/Windsor/WindsorThesis/Git repo/Thesis-Project-Python-Dependency-Conflict-Resolution/Dataset/gist/main_gist\requirements.5752919.txt (line 1))
  Obtaining dependency information for Django==3.1.5 from https://files.pythonhosted.org/packages/b2/8f/d27f35f0639103271231bc81a96ad9188e6b5bc878e140ccb0dc610ccef0/Django-3.1.5-py3-none-any.whl.metadata
  Downloading Django-3.1.5-py3-none-any.whl.metadata (3.7 kB)
Collecting pystache==0.5.4 (from -r D:/Windsor/WindsorThesis/Git repo/Thesis-Project-Python-Dependency-Conflict-Resolution/Dataset/gist/main_gist\requirements.5752919.txt (line 2))
  Downloading pystache-0.5.4.tar.gz (75 kB)
     -------------------------------------- 75.1/75.1 kB 519.1 kB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  Getting requirements to build wheel did not run successfully.
  exit code: 1
  
  [3 lines of output]
  pystache: using: version '71.0.0' of <module 'setuptools' from 'C:\\Users\\ASUS\\AppData\\Local\\Temp\\pip-build-env-0z6q5ruq\\overlay\\Lib\\site-packages\\setuptools\\__init__.py'>
  Warning: 'classifiers' should be a list, got type 'tuple'
  error in pystache setup command: use_2to3 is invalid.
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 23.2.1 -> 24.1.2
[notice] To update, run: D:\Windsor\WindsorThesis\Git repo\Thesis-Project-Python-Dependency-Conflict-Resolution\pipTest\myenv\Scripts\python.exe -m pip install --upgrade pip
