Collecting pygame==2.0.1 (from -r D:/Windsor/WindsorThesis/Git repo/Thesis-Project-Python-Dependency-Conflict-Resolution/Dataset/gist/main_gist\requirements.1521059.txt (line 1))
  Downloading pygame-2.0.1.tar.gz (5.5 MB)
     ---------------------------------------- 5.5/5.5 MB 4.1 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  Getting requirements to build wheel did not run successfully.
  exit code: 1
  
  [94 lines of output]
  
  
  WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
  Using WINDOWS configuration...
  
  Making dir :prebuilt_downloads:
  Downloading... https://www.libsdl.org/release/SDL2-devel-2.0.14-VC.zip 48d5dcd4a445410301f5575219cffb6de654edb8
  
  ---
  For help with compilation see:
      https://www.pygame.org/wiki/CompileWindows
  To contribute to pygame development see:
      https://www.pygame.org/contribute.html
  ---
  
  Traceback (most recent call last):
    File "C:\Python312\Lib\urllib\request.py", line 1344, in do_open
      h.request(req.get_method(), req.selector, req.data, headers,
    File "C:\Python312\Lib\http\client.py", line 1319, in request
      self._send_request(method, url, body, headers, encode_chunked)
    File "C:\Python312\Lib\http\client.py", line 1365, in _send_request
      self.endheaders(body, encode_chunked=encode_chunked)
    File "C:\Python312\Lib\http\client.py", line 1314, in endheaders
      self._send_output(message_body, encode_chunked=encode_chunked)
    File "C:\Python312\Lib\http\client.py", line 1074, in _send_output
      self.send(msg)
    File "C:\Python312\Lib\http\client.py", line 1018, in send
      self.connect()
    File "C:\Python312\Lib\http\client.py", line 1460, in connect
      self.sock = self._context.wrap_socket(self.sock,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Python312\Lib\ssl.py", line 455, in wrap_socket
      return self.sslsocket_class._create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Python312\Lib\ssl.py", line 1046, in _create
      self.do_handshake()
    File "C:\Python312\Lib\ssl.py", line 1317, in do_handshake
      self._sslobj.do_handshake()
  TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "D:\Windsor\WindsorThesis\Git repo\Thesis-Project-Python-Dependency-Conflict-Resolution\pipTest\myenv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "D:\Windsor\WindsorThesis\Git repo\Thesis-Project-Python-Dependency-Conflict-Resolution\pipTest\myenv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "D:\Windsor\WindsorThesis\Git repo\Thesis-Project-Python-Dependency-Conflict-Resolution\pipTest\myenv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\ASUS\AppData\Local\Temp\pip-build-env-aitbej1v\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=[])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\ASUS\AppData\Local\Temp\pip-build-env-aitbej1v\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
      self.run_setup()
    File "C:\Users\ASUS\AppData\Local\Temp\pip-build-env-aitbej1v\overlay\Lib\site-packages\setuptools\build_meta.py", line 497, in run_setup
      super().run_setup(setup_script=setup_script)
    File "C:\Users\ASUS\AppData\Local\Temp\pip-build-env-aitbej1v\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
      exec(code, locals())
    File "<string>", line 318, in <module>
    File "C:\Users\ASUS\AppData\Local\Temp\pip-install-jrq12mzj\pygame_94feb73572ab483bbff5ca10bf06905e\buildconfig\config.py", line 221, in main
      deps = CFG.main(**kwds)
             ^^^^^^^^^^^^^^^^
    File "C:\Users\ASUS\AppData\Local\Temp\pip-install-jrq12mzj\pygame_94feb73572ab483bbff5ca10bf06905e\buildconfig\config_win.py", line 559, in main
      and download_win_prebuilt.ask(**download_kwargs):
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\ASUS\AppData\Local\Temp\pip-install-jrq12mzj\pygame_94feb73572ab483bbff5ca10bf06905e\buildconfig\download_win_prebuilt.py", line 275, in ask
      update(x86=x86, x64=x64, sdl2=sdl2)
    File "C:\Users\ASUS\AppData\Local\Temp\pip-install-jrq12mzj\pygame_94feb73572ab483bbff5ca10bf06905e\buildconfig\download_win_prebuilt.py", line 258, in update
      download_prebuilts(download_dir, x86=x86, x64=x64, sdl2=sdl2)
    File "C:\Users\ASUS\AppData\Local\Temp\pip-install-jrq12mzj\pygame_94feb73572ab483bbff5ca10bf06905e\buildconfig\download_win_prebuilt.py", line 107, in download_prebuilts
      download_sha1_unzip(url, checksum, temp_dir, 1)
    File "C:\Users\ASUS\AppData\Local\Temp\pip-install-jrq12mzj\pygame_94feb73572ab483bbff5ca10bf06905e\buildconfig\download_win_prebuilt.py", line 40, in download_sha1_unzip
      response = urllib.urlopen(request).read()
                 ^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Python312\Lib\urllib\request.py", line 215, in urlopen
      return opener.open(url, data, timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Python312\Lib\urllib\request.py", line 515, in open
      response = self._open(req, data)
                 ^^^^^^^^^^^^^^^^^^^^^
    File "C:\Python312\Lib\urllib\request.py", line 532, in _open
      result = self._call_chain(self.handle_open, protocol, protocol +
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Python312\Lib\urllib\request.py", line 492, in _call_chain
      result = func(*args)
               ^^^^^^^^^^^
    File "C:\Python312\Lib\urllib\request.py", line 1392, in https_open
      return self.do_open(http.client.HTTPSConnection, req,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Python312\Lib\urllib\request.py", line 1347, in do_open
      raise URLError(err)
  urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 23.2.1 -> 24.1.2
[notice] To update, run: D:\Windsor\WindsorThesis\Git repo\Thesis-Project-Python-Dependency-Conflict-Resolution\pipTest\myenv\Scripts\python.exe -m pip install --upgrade pip
